#!/bin/bash

WINIMG=$XDG_VM_DIR/win10/win10.img

if [ -z $1 ]; then
    qemu-system-x86_64 --enable-kvm -drive driver=raw,file=$WINIMG,if=virtio -m 4096 \
        -vga qxl -device virtio-serial-pci -spice port=5999,password=qaz -device virtserialport,chardev=spicechannel0,name=com.redhat.spice.0 -chardev spicevmc,id=spicechannel0,name=vdagent \
        -cpu host \
        -net nic,model=virtio \
        -rtc base=localtime,clock=host -smp cores=4,threads=4 \
        -usb -device usb-tablet \
        -net user,smb=$HOME &
else
     WINISO=$XDG_VM_DIR/win10/Win10.iso
     VIRTISO=$XDG_VM_DIR/win10/virtio.iso

     qemu-system-x86_64 --enable-kvm -drive driver=raw,file=$WINIMG,if=virtio -m 4096 \
         -vga qxl -device virtio-serial-pci -spice port=5999,password=qaz -device virtserialport,chardev=spicechannel0,name=com.redhat.spice.0 -chardev spicevmc,id=spicechannel0,name=vdagent \
         -net nic,model=virtio -net user -cdrom $WINISO \
         -drive file=$VIRTISO,index=3,media=cdrom \
         -rtc base=localtime,clock=host -smp cores=4,threads=4 \
         -usb -device usb-tablet \
         -net user,smb=$HOME &
fi

sleep 5 && spicy -h 127.0.0.1 -p 5999 -w qaz
